/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 ./public/bananaFinal-v1.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bananaFinal-v1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.banana.geometry} material={materials.skin} />
    </group>
  )
}

useGLTF.preload('/bananaFinal-v1-transformed.glb')
